#!/bin/sh

if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then
    launchctl bootout system/com.jibeib.xinglanswipe.autogo-floatball >/dev/null 2>&1 || true
    launchctl bootout system/com.jibeib.xinglanswipe.autogo-overlay >/dev/null 2>&1 || true
fi

exit 0
